import type { EarthSkillDefinition } from "../../earth-investigation-core/src/index.ts";

function invalid(message: string): never {
  throw Object.assign(new Error(`SKILL_INVALID: ${message}`), { code: "SKILL_INVALID" });
}

export function validateEarthSkill(input: EarthSkillDefinition): EarthSkillDefinition {
  const skill = structuredClone(input);
  if (skill?.schemaVersion !== "scoutpi.earth.skill.v1") invalid("unsupported schemaVersion");
  if (!/^[a-z0-9][a-z0-9-]{2,63}$/.test(skill.skillId || "")) invalid("skillId must be a lowercase hyphenated identifier");
  if (!skill.name?.trim() || !skill.description?.trim() || skill.description.length > 500) invalid("name and a concise description are required");
  if (!Array.isArray(skill.whenToUse) || !skill.whenToUse.length || skill.whenToUse.length > 16) invalid("whenToUse needs 1-16 entries");
  if (!Array.isArray(skill.instructions) || !skill.instructions.length || skill.instructions.length > 40) invalid("instructions needs 1-40 entries");
  const text = [...skill.whenToUse, ...skill.instructions, ...(skill.safetyNotes || [])];
  if (text.some((item) => typeof item !== "string" || !item.trim() || item.length > 1000)) invalid("skill entries must be non-empty strings below 1000 characters");
  if ((skill.requiredAdapterIds || []).some((id) => !/^[a-z0-9][a-z0-9._-]{2,100}$/.test(id))) invalid("requiredAdapterIds contains an invalid id");
  return skill;
}

export function renderEarthSkill(input: EarthSkillDefinition): string {
  const skill = validateEarthSkill(input);
  const lines = [
    "<!-- Generated by ScoutPi Earth Workspace. Edit the source definition or create a new version instead of adding executable code here. -->",
    "---",
    `name: ${skill.skillId}`,
    `description: ${JSON.stringify(skill.description)}`,
    "---",
    "",
    `# ${skill.name}`,
    "",
    "## When To Use",
    "",
    ...skill.whenToUse.map((item) => `- ${item}`),
    "",
    "## Workflow",
    "",
    ...skill.instructions.map((item, index) => `${index + 1}. ${item}`),
  ];
  if (skill.requiredAdapterIds?.length) lines.push("", "## Required Tool Adapters", "", ...skill.requiredAdapterIds.map((id) => `- \`${id}\``));
  if (skill.safetyNotes?.length) lines.push("", "## Safety", "", ...skill.safetyNotes.map((item) => `- ${item}`));
  lines.push("");
  return lines.join("\n");
}
